name: "Deploy to AWS s3"
description: "Deploy a static website via AWS S3"
inputs:
  bucket:
    description: "github-action-hosting"
    required: true
  bucket-region:
    description: ""
    required: false
    defalut: "ap-southeast-1"
  dist-folder:
    description: "folder containing the file"
    required: true
outputs:
  website-url:
    description: "The URL of the deployed website."
runs:
  using: "node20"
  main: "main.js"
